//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupBranch
    {
        public int BranchId { get; set; }
        public string BranchCode { get; set; }
        public int HeadOfficeId { get; set; }
        public string BranchName { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Metropolitan { get; set; }
        public string SubMetropolitan { get; set; }
        public string Municipality { get; set; }
        public string GauPalika { get; set; }
        public string WardNo { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Web { get; set; }
        public string EmailId { get; set; }
        public string PanNo { get; set; }
        public Nullable<int> VatNo { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    
        public virtual SetupHaeadOffice SetupHaeadOffice { get; set; }
    }
}
